Fix: Move checkWatchdog() to public section
The checkWatchdog() method needs to be public as it's called from:
- CommandParser::handleMotorStatus()
- motorTask() in main.cpp

This fixes the compilation error:
'bool MotorControl::checkWatchdog()' is private within this context