Fix CDCResponse to use HWCDC instead of USBCDC
When ARDUINO_USB_CDC_ON_BOOT=1, Arduino framework creates Serial
as HWCDC type (not USBCDC type).

Compilation error:
  error: no matching function for call to 'CDCResponse::CDCResponse(HWCDC&)'
  note: no known conversion for argument 1 from 'HWCDC' to 'USBCDC&'

Fix:
- Changed CDCResponse constructor parameter from USBCDC& to HWCDC&
- Changed CDCResponse member variable from USBCDC& to HWCDC&
- Added comment explaining the HWCDC type requirement

This allows CDCResponse to work with Arduino's Serial object.